# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: getstock.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'getstock.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egetstock.proto\"\x0c\n\nStockEmpty\"v\n\x10StockInformation\x12*\n\tstockInfo\x18\x01 \x03(\x0b\x32\x17.StockInformation.Tuple\x1a\x36\n\x05Tuple\x12\x14\n\x0cwarehouse_id\x18\x01 \x01(\t\x12\x17\n\x0fwarehouse_stock\x18\x02 \x01(\t2C\n\x13GetWarehouseService\x12,\n\x08getStock\x12\x0b.StockEmpty\x1a\x11.StockInformation\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'getstock_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOCKEMPTY']._serialized_start=18
  _globals['_STOCKEMPTY']._serialized_end=30
  _globals['_STOCKINFORMATION']._serialized_start=32
  _globals['_STOCKINFORMATION']._serialized_end=150
  _globals['_STOCKINFORMATION_TUPLE']._serialized_start=96
  _globals['_STOCKINFORMATION_TUPLE']._serialized_end=150
  _globals['_GETWAREHOUSESERVICE']._serialized_start=152
  _globals['_GETWAREHOUSESERVICE']._serialized_end=219
# @@protoc_insertion_point(module_scope)
